### ISSUE TITLE
Overflade klasse (funktion og udseende) (#U3, #U4, #U5) (2 timer)

### ISSUE THREAD

**Issue by ExtraUnity** [cecilianygaard/Spiludvikling#14]
Overfladeklassens består af en liste af linjesegmenter, som har deres egen klasse, og en liste af landingsplatforme, som også er inkluderet i listen af linjesegmenter. Klassen skal have en funktion, der tegner selve overfladen ud fra dens arraylister.

Metoderne i overfladeklassen kommer til at håndtere kollisionen mellem rumskibet og sig selv(med specielle cases for landingsplatformene), såvel som at tegne selve overfladen.

Overfladeklassens tegnemetode kommer til at tegne overfladen som en PShape mellem alle punkterne i linjesegmenterne og de nederste hjørner af skærmen. Derudover bliver landingsplatformene tegnet ovenpå.

**Comment by Simon220902** [comment]
Estimeret: 2 timer
Brugt: 5 timer
Dog har jeg også tilføjet en masse ekstra funktionalitet end den der blev beskrevet, nemlig at den kan læse fra en fil, at man kan lave flere levels m.m.
