### ISSUE TITLE
Linjesegmenter klasse (funktion og udseende) (#U3) (0.5 time)

### ISSUE THREAD

**Issue by ExtraUnity** [cecilianygaard/Spiludvikling#19]
Linjesegmenternes klasse består af en array af to PVectorer.

Linjesegmenternes tegnemetode tegner en linje mellem de to punkter.

**Comment by Simon220902** [comment]
Grundet andre designbeslutninger blev denne task overflødig, men lad os regne med at dens tid blev brugt på den anden task omhandlende overfladen.
