### ISSUE TITLE
#U5 Overfladens interaktion med rumskibet (udseende)

### ISSUE THREAD

**Issue by Simon220902** [cecilianygaard/Spiludvikling#5]
Når rumskibet er tæt på overfladen og den bruger sin raket mod overfladen skal der komme støv fra overfladen.

Når rumskibet kollidere med overfladen og det ikke er en succesfuld landing skal den gå i stykker og spredes.

**Comment by cecilianygaard** [comment]
Når rumskibet kommer inden for en vis afstand fra overfladen zoomer kameraet ind.
